apiVersion: appdynamics.com/v1alpha1
kind: Clusteragent
metadata:
  name: k8s-cluster-agent
  namespace: appdynamics
spec:
  appName: "morgans_uat"
  controllerUrl: "https://morgans-pov.saas.appdynamics.com"
  account: "morgans-pov"
  # docker image info
  image: "docker.io/appdynamics/cluster-agent:latest"
  serviceAccountName: appdynamics-cluster-agent
  #START ClusterAgent Logging Configuration
  logLevel: DEBUG
  logFileSizeMb: 7
  logFileBackups: 6
  # enable Java auto instrumentation 
  nsToMonitor:
    - "default"
    - "appdynamics"
  instrumentationMethod: Env
  nsToInstrumentRegex: default|appdynamics
  defaultAppName: Morgans-UAT
  resourcesToInstrument: [Deployment,StatefulSet]
  imageInfo:
    java:
      image: "docker.io/appdynamics/java-agent:latest"
      agentMountPath: /opt/appdynamics
  ### Uncomment the following two lines if you need pull secrets
  #imagePullSecrets:
  #  name: "<your-docker-pull-secret-name>"